name: algitsin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  animated_splash_screen: ^1.1.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^2.5.4
  count_stepper: ^0.0.4
  file_picker: ^4.2.5
  firebase_auth: ^3.2.0
  firebase_core: ^1.8.0
  firebase_messaging: ^11.2.0
  firebase_storage: ^10.2.4
  flashy_tab_bar2: ^0.0.3
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_styled_toast: ^2.0.0
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  image_picker: ^0.8.4+4
  like_button: ^2.0.3
  photo_view: ^0.13.0
  provider: ^6.0.1
  sliding_up_panel: ^2.0.0+1
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
dependency_overrides:
  quiver: ^3.0.1+1

flutter:

  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
